 # 开发环境配置
server:
  servlet:
    # 应用的访问路径
    context-path: /pdf
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    use-openssl: false
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
  max-http-header-size: 10KB
# 日志配置
#logging:
#  level:
#    org.springframework: info
#    org.apache.catalina.core.ContainerBase.[Catalina].[localhost]: info
logging:
  level:
    root: debug

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
    prefix:
      classpath: /templates/ # 访问template下的html文件需要配置模板，映射
    suffix: .html
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: prod
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  50MB
       # 设置总上传的文件大小
       max-request-size:  50MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
